---
Resources:
      

  MySecondInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "My-EC2-Instance-2"

  MySecondInstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MySecondInstance


  MyThirdInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: "My-EC2-Instance-3"
