Description: CloudFormation template for s3 bucket 
    
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating a S3 bucket from CloudFormation
    Properties:
      BucketName: demo-sr-my-new-bucket-11-feb-2023
      VersioningConfiguration:
        Status: Enabled
Outputs:
  MyS3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref MyS3Bucket       
  MyS3BucketArn:
    Description: ARN for the new bucket.
    Value: !GetAtt MyS3Bucket.Arn
  TestOutputName1:
    Description: Demonstrates the usage of Outputs.
    Value: "Test Output Value1"
  TestGLUrl:
    Description: Contains GreatLearning URL.
    Value: "https://www.mygreatlearning.com/"
